# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vtpl_api
from vtpl_api.models.fancy_lp_events_response import FancyLPEventsResponse  # noqa: E501
from vtpl_api.rest import ApiException


class TestFancyLPEventsResponse(unittest.TestCase):
    """FancyLPEventsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFancyLPEventsResponse(self):
        """Test FancyLPEventsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vtpl_api.models.fancy_lp_events_response.FancyLPEventsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
