# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vtpl_api
from vtpl_api.models.crowd_formation_events_response import CrowdFormationEventsResponse  # noqa: E501
from vtpl_api.rest import ApiException


class TestCrowdFormationEventsResponse(unittest.TestCase):
    """CrowdFormationEventsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCrowdFormationEventsResponse(self):
        """Test CrowdFormationEventsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vtpl_api.models.crowd_formation_events_response.CrowdFormationEventsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
