# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vtpl_api
from vtpl_api.models.people_on_road_events_response import PeopleOnRoadEventsResponse  # noqa: E501
from vtpl_api.rest import ApiException


class TestPeopleOnRoadEventsResponse(unittest.TestCase):
    """PeopleOnRoadEventsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPeopleOnRoadEventsResponse(self):
        """Test PeopleOnRoadEventsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vtpl_api.models.people_on_road_events_response.PeopleOnRoadEventsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
