# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vtpl_api
from vtpl_api.models.schedule_source import ScheduleSource  # noqa: E501
from vtpl_api.rest import ApiException


class TestScheduleSource(unittest.TestCase):
    """ScheduleSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduleSource(self):
        """Test ScheduleSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vtpl_api.models.schedule_source.ScheduleSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
