# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import vtpl_api
from vtpl_api.models.sub_systems_response import SubSystemsResponse  # noqa: E501
from vtpl_api.rest import ApiException


class TestSubSystemsResponse(unittest.TestCase):
    """SubSystemsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubSystemsResponse(self):
        """Test SubSystemsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = vtpl_api.models.sub_systems_response.SubSystemsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
