# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Command(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'capability': 'Capability',
        'command': 'Commands'
    }

    attribute_map = {
        'capability': 'capability',
        'command': 'command'
    }

    def __init__(self, capability=None, command=None):  # noqa: E501
        """Command - a model defined in OpenAPI"""  # noqa: E501

        self._capability = None
        self._command = None
        self.discriminator = None

        if capability is not None:
            self.capability = capability
        if command is not None:
            self.command = command

    @property
    def capability(self):
        """Gets the capability of this Command.  # noqa: E501


        :return: The capability of this Command.  # noqa: E501
        :rtype: Capability
        """
        return self._capability

    @capability.setter
    def capability(self, capability):
        """Sets the capability of this Command.


        :param capability: The capability of this Command.  # noqa: E501
        :type: Capability
        """

        self._capability = capability

    @property
    def command(self):
        """Gets the command of this Command.  # noqa: E501


        :return: The command of this Command.  # noqa: E501
        :rtype: Commands
        """
        return self._command

    @command.setter
    def command(self, command):
        """Sets the command of this Command.


        :param command: The command of this Command.  # noqa: E501
        :type: Commands
        """

        self._command = command

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Command):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
