# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DestinationEndPoint(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'destination_list': 'list[DestinationEndPointDestinationList]',
        'extras': 'list[Extra]'
    }

    attribute_map = {
        'destination_list': 'destinationList',
        'extras': 'extras'
    }

    def __init__(self, destination_list=None, extras=None):  # noqa: E501
        """DestinationEndPoint - a model defined in OpenAPI"""  # noqa: E501

        self._destination_list = None
        self._extras = None
        self.discriminator = None

        if destination_list is not None:
            self.destination_list = destination_list
        if extras is not None:
            self.extras = extras

    @property
    def destination_list(self):
        """Gets the destination_list of this DestinationEndPoint.  # noqa: E501


        :return: The destination_list of this DestinationEndPoint.  # noqa: E501
        :rtype: list[DestinationEndPointDestinationList]
        """
        return self._destination_list

    @destination_list.setter
    def destination_list(self, destination_list):
        """Sets the destination_list of this DestinationEndPoint.


        :param destination_list: The destination_list of this DestinationEndPoint.  # noqa: E501
        :type: list[DestinationEndPointDestinationList]
        """

        self._destination_list = destination_list

    @property
    def extras(self):
        """Gets the extras of this DestinationEndPoint.  # noqa: E501


        :return: The extras of this DestinationEndPoint.  # noqa: E501
        :rtype: list[Extra]
        """
        return self._extras

    @extras.setter
    def extras(self, extras):
        """Sets the extras of this DestinationEndPoint.


        :param extras: The extras of this DestinationEndPoint.  # noqa: E501
        :type: list[Extra]
        """

        self._extras = extras

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DestinationEndPoint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
