# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class EvidenceConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'source': 'ScheduleSource',
        'count': 'int',
        'pre_event_sec': 'int',
        'post_event_sec': 'int'
    }

    attribute_map = {
        'source': 'source',
        'count': 'count',
        'pre_event_sec': 'preEventSec',
        'post_event_sec': 'postEventSec'
    }

    def __init__(self, source=None, count=1, pre_event_sec=0, post_event_sec=0):  # noqa: E501
        """EvidenceConfig - a model defined in OpenAPI"""  # noqa: E501

        self._source = None
        self._count = None
        self._pre_event_sec = None
        self._post_event_sec = None
        self.discriminator = None

        if source is not None:
            self.source = source
        if count is not None:
            self.count = count
        if pre_event_sec is not None:
            self.pre_event_sec = pre_event_sec
        if post_event_sec is not None:
            self.post_event_sec = post_event_sec

    @property
    def source(self):
        """Gets the source of this EvidenceConfig.  # noqa: E501


        :return: The source of this EvidenceConfig.  # noqa: E501
        :rtype: ScheduleSource
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this EvidenceConfig.


        :param source: The source of this EvidenceConfig.  # noqa: E501
        :type: ScheduleSource
        """

        self._source = source

    @property
    def count(self):
        """Gets the count of this EvidenceConfig.  # noqa: E501


        :return: The count of this EvidenceConfig.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this EvidenceConfig.


        :param count: The count of this EvidenceConfig.  # noqa: E501
        :type: int
        """

        self._count = count

    @property
    def pre_event_sec(self):
        """Gets the pre_event_sec of this EvidenceConfig.  # noqa: E501


        :return: The pre_event_sec of this EvidenceConfig.  # noqa: E501
        :rtype: int
        """
        return self._pre_event_sec

    @pre_event_sec.setter
    def pre_event_sec(self, pre_event_sec):
        """Sets the pre_event_sec of this EvidenceConfig.


        :param pre_event_sec: The pre_event_sec of this EvidenceConfig.  # noqa: E501
        :type: int
        """

        self._pre_event_sec = pre_event_sec

    @property
    def post_event_sec(self):
        """Gets the post_event_sec of this EvidenceConfig.  # noqa: E501


        :return: The post_event_sec of this EvidenceConfig.  # noqa: E501
        :rtype: int
        """
        return self._post_event_sec

    @post_event_sec.setter
    def post_event_sec(self, post_event_sec):
        """Sets the post_event_sec of this EvidenceConfig.


        :param post_event_sec: The post_event_sec of this EvidenceConfig.  # noqa: E501
        :type: int
        """

        self._post_event_sec = post_event_sec

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EvidenceConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
