# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class FaceFeatureResponseCommand(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'capability': 'Capability',
        'command': 'Commands',
        'total_faces': 'int',
        'face_snap': 'FaceSnap',
        'snap_upload_model': 'SnapUploadModel'
    }

    attribute_map = {
        'capability': 'capability',
        'command': 'command',
        'total_faces': 'totalFaces',
        'face_snap': 'faceSnap',
        'snap_upload_model': 'snapUploadModel'
    }

    def __init__(self, capability=None, command=None, total_faces=0, face_snap=None, snap_upload_model=None):  # noqa: E501
        """FaceFeatureResponseCommand - a model defined in OpenAPI"""  # noqa: E501

        self._capability = None
        self._command = None
        self._total_faces = None
        self._face_snap = None
        self._snap_upload_model = None
        self.discriminator = None

        if capability is not None:
            self.capability = capability
        if command is not None:
            self.command = command
        if total_faces is not None:
            self.total_faces = total_faces
        if face_snap is not None:
            self.face_snap = face_snap
        if snap_upload_model is not None:
            self.snap_upload_model = snap_upload_model

    @property
    def capability(self):
        """Gets the capability of this FaceFeatureResponseCommand.  # noqa: E501


        :return: The capability of this FaceFeatureResponseCommand.  # noqa: E501
        :rtype: Capability
        """
        return self._capability

    @capability.setter
    def capability(self, capability):
        """Sets the capability of this FaceFeatureResponseCommand.


        :param capability: The capability of this FaceFeatureResponseCommand.  # noqa: E501
        :type: Capability
        """

        self._capability = capability

    @property
    def command(self):
        """Gets the command of this FaceFeatureResponseCommand.  # noqa: E501


        :return: The command of this FaceFeatureResponseCommand.  # noqa: E501
        :rtype: Commands
        """
        return self._command

    @command.setter
    def command(self, command):
        """Sets the command of this FaceFeatureResponseCommand.


        :param command: The command of this FaceFeatureResponseCommand.  # noqa: E501
        :type: Commands
        """

        self._command = command

    @property
    def total_faces(self):
        """Gets the total_faces of this FaceFeatureResponseCommand.  # noqa: E501


        :return: The total_faces of this FaceFeatureResponseCommand.  # noqa: E501
        :rtype: int
        """
        return self._total_faces

    @total_faces.setter
    def total_faces(self, total_faces):
        """Sets the total_faces of this FaceFeatureResponseCommand.


        :param total_faces: The total_faces of this FaceFeatureResponseCommand.  # noqa: E501
        :type: int
        """

        self._total_faces = total_faces

    @property
    def face_snap(self):
        """Gets the face_snap of this FaceFeatureResponseCommand.  # noqa: E501


        :return: The face_snap of this FaceFeatureResponseCommand.  # noqa: E501
        :rtype: FaceSnap
        """
        return self._face_snap

    @face_snap.setter
    def face_snap(self, face_snap):
        """Sets the face_snap of this FaceFeatureResponseCommand.


        :param face_snap: The face_snap of this FaceFeatureResponseCommand.  # noqa: E501
        :type: FaceSnap
        """

        self._face_snap = face_snap

    @property
    def snap_upload_model(self):
        """Gets the snap_upload_model of this FaceFeatureResponseCommand.  # noqa: E501


        :return: The snap_upload_model of this FaceFeatureResponseCommand.  # noqa: E501
        :rtype: SnapUploadModel
        """
        return self._snap_upload_model

    @snap_upload_model.setter
    def snap_upload_model(self, snap_upload_model):
        """Sets the snap_upload_model of this FaceFeatureResponseCommand.


        :param snap_upload_model: The snap_upload_model of this FaceFeatureResponseCommand.  # noqa: E501
        :type: SnapUploadModel
        """

        self._snap_upload_model = snap_upload_model

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FaceFeatureResponseCommand):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
