# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class FaceCategory(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'caption': 'str',
        'color': 'str'
    }

    attribute_map = {
        'id': '_id',
        'caption': 'caption',
        'color': 'color'
    }

    def __init__(self, id=None, caption=None, color=None):  # noqa: E501
        """FaceCategory - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._caption = None
        self._color = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if caption is not None:
            self.caption = caption
        if color is not None:
            self.color = color

    @property
    def id(self):
        """Gets the id of this FaceCategory.  # noqa: E501


        :return: The id of this FaceCategory.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FaceCategory.


        :param id: The id of this FaceCategory.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def caption(self):
        """Gets the caption of this FaceCategory.  # noqa: E501


        :return: The caption of this FaceCategory.  # noqa: E501
        :rtype: str
        """
        return self._caption

    @caption.setter
    def caption(self, caption):
        """Sets the caption of this FaceCategory.


        :param caption: The caption of this FaceCategory.  # noqa: E501
        :type: str
        """

        self._caption = caption

    @property
    def color(self):
        """Gets the color of this FaceCategory.  # noqa: E501


        :return: The color of this FaceCategory.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this FaceCategory.


        :param color: The color of this FaceCategory.  # noqa: E501
        :type: str
        """

        self._color = color

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FaceCategory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
