# coding: utf-8

"""
    Engine api

    Engine APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SubSystemStatusCommand(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'capability': 'list[Capability]',
        'command': 'Commands',
        'sub_system_id': 'str'
    }

    attribute_map = {
        'capability': 'capability',
        'command': 'command',
        'sub_system_id': 'subSystemId'
    }

    def __init__(self, capability=None, command=None, sub_system_id=None):  # noqa: E501
        """SubSystemStatusCommand - a model defined in OpenAPI"""  # noqa: E501

        self._capability = None
        self._command = None
        self._sub_system_id = None
        self.discriminator = None

        if capability is not None:
            self.capability = capability
        if command is not None:
            self.command = command
        if sub_system_id is not None:
            self.sub_system_id = sub_system_id

    @property
    def capability(self):
        """Gets the capability of this SubSystemStatusCommand.  # noqa: E501


        :return: The capability of this SubSystemStatusCommand.  # noqa: E501
        :rtype: list[Capability]
        """
        return self._capability

    @capability.setter
    def capability(self, capability):
        """Sets the capability of this SubSystemStatusCommand.


        :param capability: The capability of this SubSystemStatusCommand.  # noqa: E501
        :type: list[Capability]
        """

        self._capability = capability

    @property
    def command(self):
        """Gets the command of this SubSystemStatusCommand.  # noqa: E501


        :return: The command of this SubSystemStatusCommand.  # noqa: E501
        :rtype: Commands
        """
        return self._command

    @command.setter
    def command(self, command):
        """Sets the command of this SubSystemStatusCommand.


        :param command: The command of this SubSystemStatusCommand.  # noqa: E501
        :type: Commands
        """

        self._command = command

    @property
    def sub_system_id(self):
        """Gets the sub_system_id of this SubSystemStatusCommand.  # noqa: E501


        :return: The sub_system_id of this SubSystemStatusCommand.  # noqa: E501
        :rtype: str
        """
        return self._sub_system_id

    @sub_system_id.setter
    def sub_system_id(self, sub_system_id):
        """Sets the sub_system_id of this SubSystemStatusCommand.


        :param sub_system_id: The sub_system_id of this SubSystemStatusCommand.  # noqa: E501
        :type: str
        """

        self._sub_system_id = sub_system_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SubSystemStatusCommand):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
